export const actionTypes = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: 'LOGOUT',

    PROFILEINFO_REQUEST: 'PROFILEINFO_REQUEST',
    PROFILEINFO_SUCCESS: 'PROFILEINFO_SUCCESS',
    PROFILEINFO_FAILURE: 'PROFILEINFO_FAILURE',

    BLOGINFO_REQUEST: 'BLOGINFO_REQUEST',
    BLOGINFO_SUCCESS: 'BLOGINFO_SUCCESS',
    BLOGINFO_FAILURE: 'BLOGINFO_FAILURE',

    UPDATEUSER_REQUEST: 'UPDATEUSER_REQUEST',
    UPDATEUSER_SUCCESS: 'UPDATEUSER_SUCCESS',
    UPDATEUSER_FAILURE: 'UPDATEUSER_FAILURE',

    OTHERUSER_REQUEST: 'OTHERUSER_REQUEST',
    OTHERUSER_SUCCESS: 'OTHERUSER_SUCCESS',
    OTHERUSER_FAILURE: 'OTHERUSER_FAILURE',
};